export { IndustryCalculator } from "./industry-calculator"
export { IndustryCTA } from "./industry-cta"
export { CompetitiveAudit } from "./competitive-audit"
export { IndustryBenchmarks } from "./industry-benchmarks"
export { getIndustryConfig } from "./industry-config"
export type { IndustryData, CalculatorConfig, IndustryCTAConfig, IndustryBenchmark } from "./industry-config"
